### ISSUE TITLE
public and private ips reversed

### ISSUE THREAD

**Issue by stevesmename** [million12/linodeapi#11]
When attempting to run the script, the public and private IP addresses were incorrect. I'd suggest using the ISPUBLIC from the Linode API response.

**Comment by pozgo** [comment]
Hi,
Please make sure that you are having those two sections in your cloud-config.yaml file:  
<pre># Environment Variables
  - path: /etc/environment
    content: |
      COREOS_PUBLIC_IPV4=$public_ipv4
      COREOS_PRIVATE_IPV4=$private_ipv4</pre>
and
<pre># Linode Private network tweak
  - path: /etc/systemd/network/50-static.network
    content: |
      [Match]
      Name=eth0
      [Network]
      Address=$public_ipv4/24
      Address=$private_ipv4/17
      Gateway=$gateway.1
      DNS=8.8.8.8
      DNS=8.8.4.4</pre>

Those two sections are going to be modified after core os is deployed on Linode accordingly to network settings created during the process of deployment.

**Comment by pozgo** [comment]
I have used linode api to deploy my test cluster and all works fine. Please use settings from above in network section. 

Closing...

**Comment by stevesmename** [comment]
Maybe this will help better explain the Linode provisioning issue that helped me find and resolve the issue of why provisioning was not working. For me, the Private IP was the first IP and the Public IP was the second IP. I ran the script a few times successfully after finding the problem, prior it would loop through "Waiting for server to boot...". The provision failed because it was hitting the Private IP instead of the Public IP. 

```
diff --git a/linode b/linode
index ac05ad7..1476a8e 100755
--- a/linode
+++ b/linode
@@ -288,8 +288,8 @@ log "Configuring node networking..."
 $LINODEAPI -c linode.ip.addprivate -d LINODEID=$linodeid 1>/dev/null
 # Contains pure list of IP addresses, one per-line. The 1st one is public.
 iplist=$($LINODEAPI -c linode.ip.list -d LinodeID=$linodeid | grep -E 'IPADDRESS\W' | sed -E 's/[^\.0-9]//g')
-publicip=$(echo "$iplist" | sed -n 1p) # get the 1st IP addr
-privateip=$(echo "$iplist" | sed -n 2p) # get the 2nd IP addr
+privateip=$(echo "$iplist" | sed -n 1p) # get the 1st IP addr
+publicip=$(echo "$iplist" | sed -n 2p) # get the 2nd IP addr
 gateway_net=$(echo $privateip | awk -F. '{print $1 "." $2 "." $3}') # private IP, but with no last segment
 log "Public IP: ${bold}${white}$publicip${reset}, private IP: ${bold}${white}$privateip${reset}, gateway: ${bold}${white}$gateway_net.1${reset}."
```

**Comment by dwaite** [comment]
These are also reversed for me

**Comment by ryzy** [comment]
Should be fixed by now, let us know it works for you, @stevesmename
