### ISSUE TITLE
IPs reversed, cannot connect to server on boot

### ISSUE THREAD

**Issue by dwaite** [million12/linodeapi#12]
The public and private IP addresses are reversed when running through the script:

[LINODE API 11:10:20] Public IP: 192.168.161.141, private IP: 45.56.10.12, gateway:  45.56.10.1.

The result of this is that the sshpass polling of the server never succeeds - it is polling a 192.168.x.x address.

**Comment by ryzy** [comment]
Yes, that's the same as #11 
@pozgo is working on that ;)

**Comment by ryzy** [comment]
Should be fixed by now, let us know it works for you, @dwaite
