### ISSUE TITLE
Compile custom kernel for Linode 

### ISSUE THREAD

**Issue by stevesmename** [million12/linodeapi#19]
It's my understanding that the loaded kernel is default configurations from CoreOS, ignoring Xen optimizations defined by Linode.

> Your kernel must be properly configured to run under our environment. Some required configuration options may include:
> - CONFIG_PARAVIRT=y
> - CONFIG_PARAVIRT_GUEST=y
> - CONFIG_PARAVIRT_CLOCK=y
> - CONFIG_XEN=y
> - CONFIG_XEN_BLKDEV_FRONTEND=y
> - CONFIG_XEN_NETDEV_FRONTEND=y
> - CONFIG_XEN_SCRUB_PAGES=y
> - CONFIG_HVC_XEN=y

https://github.com/coreos/linux
https://www.linode.com/docs/tools-reference/custom-kernels-distros/run-a-custom-compiled-kernel-with-pvgrub/

**Comment by pozgo** [comment]
Hi, 
No we are not doing anything with the image that is downloaded through official CoreOS install script. 
But as far as I remember CoreOS was Xen ready and all kernel flags were set there already. But again I might be wrong. We were using CoreOS on Linode for over a year and all seems ok so far. 

If you are sure it's not there please feel free to add it and send us PR. I'm quite busy at the moment and wouldn't be possible for me to find some spare time to check that in detail and implement if needed be. Sorry.

**Comment by stevesmename** [comment]
I can't really confirm this being an issue either. I think it might be better to not be on a custom kernel (if possible) for support issues.
